import type { Ticket, Topic } from "@/types/database";

const phpTickets: Ticket[] = [
  // === EASY ===
  {
    id: "php-1",
    type: "multiple_choice",
    difficulty: "easy",
    topic: "php",
    title: "Missing semicolon",
    description: "What is wrong with this PHP code?",
    code_snippet: '$name = "John"\necho $name;',
    options: [
      "A) Missing semicolon after string assignment",
      "B) Wrong variable syntax",
      "C) echo needs parentheses",
      "D) String should use single quotes",
    ],
    correct_answer: "A",
    explanation: "PHP statements must end with a semicolon.",
  },
  {
    id: "php-2",
    type: "multiple_choice",
    difficulty: "easy",
    topic: "php",
    title: "Array function error",
    description: "Which function correctly counts array elements?",
    code_snippet: '$arr = [1, 2, 3, 4, 5];\n$total = ???($arr);',
    options: ["A) length($arr)", "B) count($arr)", "C) size($arr)", "D) sizeof($arr)"],
    correct_answer: "B",
    explanation: "count() returns the number of elements in an array.",
  },
  {
    id: "php-3",
    type: "fill_in_blank",
    difficulty: "easy",
    topic: "php",
    title: "String concatenation",
    description: "What operator concatenates strings in PHP?",
    code_snippet: '$greeting = "Hello" ??? " World";',
    correct_answer: ".",
    explanation: "PHP uses the dot (.) operator for string concatenation.",
  },
  {
    id: "php-4",
    type: "multiple_choice",
    difficulty: "easy",
    topic: "php",
    title: "Array push",
    description: "How to add an element to the end of an array?",
    code_snippet: "$fruits = ['apple', 'banana'];\n// Add 'cherry' to the end",
    options: [
      "A) $fruits[] = 'cherry'",
      "B) $fruits += 'cherry'",
      "C) $fruits->push('cherry')",
      "D) array_add($fruits, 'cherry')",
    ],
    correct_answer: "A",
    explanation: "Using $arr[] = value appends to the array. array_push() also works.",
  },
  {
    id: "php-5",
    type: "multiple_choice",
    difficulty: "easy",
    topic: "php",
    title: "echo vs print",
    description: "What is the key difference between echo and print in PHP?",
    code_snippet: 'echo "Hello";\nprint "Hello";',
    options: [
      "A) echo can take multiple arguments, print cannot",
      "B) print is faster than echo",
      "C) echo returns a value, print does not",
      "D) They are completely identical",
    ],
    correct_answer: "A",
    explanation: "echo can take multiple comma-separated arguments. print takes only one and returns 1.",
  },
  {
    id: "php-6",
    type: "fill_in_blank",
    difficulty: "easy",
    topic: "php",
    title: "Variable declaration",
    description: "What symbol is used to declare variables in PHP?",
    code_snippet: '???name = "Alice";',
    correct_answer: "$",
    explanation: "PHP variables start with the dollar sign ($).",
  },
  {
    id: "php-7",
    type: "multiple_choice",
    difficulty: "easy",
    topic: "php",
    title: "isset vs empty",
    description: "What does isset() return for an empty string?",
    code_snippet: '$val = "";\nvar_dump(isset($val));\nvar_dump(empty($val));',
    options: [
      "A) true, true",
      "B) false, true",
      "C) true, false",
      "D) false, false",
    ],
    correct_answer: "A",
    explanation: 'isset() returns true because $val exists. empty() returns true because "" is considered empty.',
  },
  {
    id: "php-8",
    type: "multiple_choice",
    difficulty: "easy",
    topic: "php",
    title: "Array key access",
    description: "What happens when you access a non-existent array key?",
    code_snippet: "$data = ['name' => 'John'];\necho $data['age'];",
    options: [
      "A) Outputs nothing and throws a warning",
      "B) Fatal error",
      "C) Outputs 0",
      "D) Outputs null without any warning",
    ],
    correct_answer: "A",
    explanation: "Accessing undefined keys in PHP triggers an E_WARNING (or E_NOTICE in older versions).",
  },
  // === MEDIUM ===
  {
    id: "php-9",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "php",
    title: "Type comparison bug",
    description: "What does this comparison return?",
    code_snippet: 'var_dump(0 == "php");',
    options: ["A) bool(true)", "B) bool(false)", "C) Error", "D) NULL"],
    correct_answer: "A",
    explanation: "PHP loose comparison converts 'php' to 0, so 0 == 0 is true.",
  },
  {
    id: "php-10",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "php",
    title: "Scope issue",
    description: "What will this output?",
    code_snippet: '$x = 10;\nfunction test() {\n  echo $x;\n}\ntest();',
    options: [
      "A) 10",
      "B) Nothing (undefined variable warning)",
      "C) Error: undefined variable",
      "D) NULL",
    ],
    correct_answer: "B",
    explanation: "PHP functions have their own scope. $x is not accessible without global keyword.",
  },
  {
    id: "php-11",
    type: "fill_in_blank",
    difficulty: "medium",
    topic: "php",
    title: "Null coalescing",
    description: "What operator provides a default value for null?",
    code_snippet: '$name = $user["name"] ??? "Anonymous";',
    correct_answer: "??",
    explanation: "The null coalescing operator ?? returns the right operand if the left is null.",
  },
  {
    id: "php-12",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "php",
    title: "Laravel N+1 query",
    description: "What pattern fixes the N+1 problem here?",
    code_snippet: '$posts = Post::all();\nforeach ($posts as $post) {\n  echo $post->author->name;\n}',
    options: [
      "A) Post::with('author')->get()",
      "B) Post::join('author')->get()",
      "C) Post::has('author')->get()",
      "D) Post::load('author')->get()",
    ],
    correct_answer: "A",
    explanation: "Eager loading with with() loads related models in a single query.",
  },
  {
    id: "php-13",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "php",
    title: "Static vs self",
    description: "What is the difference between static:: and self:: in PHP?",
    code_snippet: "class Base {\n  protected static $name = 'Base';\n  public function getName() {\n    return static::$name;\n  }\n}\nclass Child extends Base {\n  protected static $name = 'Child';\n}\necho (new Child)->getName();",
    options: [
      "A) Outputs 'Child' - static:: uses late static binding",
      "B) Outputs 'Base' - self:: resolves at compile time",
      "C) Fatal error",
      "D) Outputs both 'Base' and 'Child'",
    ],
    correct_answer: "A",
    explanation: "static:: enables late static binding, resolving to the calling class at runtime.",
  },
  {
    id: "php-14",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "php",
    title: "Array merge gotcha",
    description: "What is the output?",
    code_snippet: "$a = ['x' => 1, 'y' => 2];\n$b = ['y' => 3, 'z' => 4];\n$c = array_merge($a, $b);\nprint_r($c);",
    options: [
      "A) ['x' => 1, 'y' => 3, 'z' => 4]",
      "B) ['x' => 1, 'y' => 2, 'z' => 4]",
      "C) ['x' => 1, 'y' => 2, 'y' => 3, 'z' => 4]",
      "D) Error: duplicate key",
    ],
    correct_answer: "A",
    explanation: "array_merge overwrites string keys with later values. $b's 'y' => 3 overwrites $a's 'y' => 2.",
  },
  {
    id: "php-15",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "php",
    title: "Ternary vs null coalescing",
    description: "What is the difference in output?",
    code_snippet: "$x = 0;\necho $x ?: 'default';    // Line A\necho $x ?? 'default';    // Line B",
    options: [
      "A) Line A: 'default', Line B: 0",
      "B) Line A: 0, Line B: 'default'",
      "C) Both output 'default'",
      "D) Both output 0",
    ],
    correct_answer: "A",
    explanation: "?: checks truthiness (0 is falsy). ?? checks null only (0 is not null).",
  },
  {
    id: "php-16",
    type: "fill_in_blank",
    difficulty: "medium",
    topic: "php",
    title: "Type declaration",
    description: "What return type means the function returns nothing?",
    code_snippet: "function logMessage(string $msg): ??? {\n  echo $msg;\n}",
    correct_answer: "void",
    explanation: "The void return type indicates the function does not return a value.",
  },
  {
    id: "php-17",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "php",
    title: "strpos pitfall",
    description: "Why is this code buggy?",
    code_snippet: '$haystack = "Hello World";\nif (strpos($haystack, "Hello")) {\n  echo "Found!";\n}',
    options: [
      'A) strpos returns 0 for "Hello" which is falsy',
      "B) strpos doesn't work with strings",
      "C) Missing third parameter",
      "D) Should use str_contains instead",
    ],
    correct_answer: "A",
    explanation: "strpos returns 0 (position of match), which evaluates to false. Use !== false to check.",
  },
  // === HARD ===
  {
    id: "php-18",
    type: "multiple_choice",
    difficulty: "hard",
    topic: "php",
    title: "Reference vs value",
    description: "What is the output?",
    code_snippet: '$a = [1, 2, 3];\nforeach ($a as &$v) {\n  $v *= 2;\n}\nforeach ($a as $v) {\n  // ...\n}\nprint_r($a);',
    options: [
      "A) [2, 4, 6]",
      "B) [2, 4, 4]",
      "C) [1, 2, 3]",
      "D) Error",
    ],
    correct_answer: "B",
    explanation: "After the first loop, $v is still a reference to the last element. The second loop overwrites it.",
  },
  {
    id: "php-19",
    type: "multiple_choice",
    difficulty: "hard",
    topic: "php",
    title: "SQL Injection vulnerability",
    description: "Which code is vulnerable to SQL injection?",
    code_snippet: '// Option A\n$stmt = $pdo->prepare("SELECT * FROM users WHERE id = ?");\n$stmt->execute([$id]);\n\n// Option B\n$result = $pdo->query("SELECT * FROM users WHERE id = " . $id);',
    options: [
      "A) Option A is vulnerable",
      "B) Option B is vulnerable",
      "C) Both are vulnerable",
      "D) Neither is vulnerable",
    ],
    correct_answer: "B",
    explanation: "Option B directly concatenates user input into the query string.",
  },
  {
    id: "php-20",
    type: "multiple_choice",
    difficulty: "hard",
    topic: "php",
    title: "Object cloning trap",
    description: "What is the output?",
    code_snippet: "$a = new stdClass();\n$a->items = [1, 2, 3];\n$b = clone $a;\n$b->items[] = 4;\necho count($a->items);",
    options: [
      "A) 3",
      "B) 4",
      "C) Error",
      "D) Depends on PHP version",
    ],
    correct_answer: "A",
    explanation: "clone creates a shallow copy. Arrays are value types in PHP, so $b gets its own copy of items.",
  },
  {
    id: "php-21",
    type: "multiple_choice",
    difficulty: "hard",
    topic: "php",
    title: "Laravel mass assignment",
    description: "What vulnerability does this code expose?",
    code_snippet: "class User extends Model {\n  // No $fillable or $guarded\n}\n\n// Controller\nUser::create($request->all());",
    options: [
      "A) Mass assignment - users can set any column",
      "B) SQL injection",
      "C) XSS attack",
      "D) CSRF vulnerability",
    ],
    correct_answer: "A",
    explanation: "Without $fillable or $guarded, all columns are mass-assignable including sensitive ones like is_admin.",
  },
  {
    id: "php-22",
    type: "multiple_choice",
    difficulty: "hard",
    topic: "php",
    title: "Floating point precision",
    description: "What is the output?",
    code_snippet: "$total = 0.1 + 0.2;\necho $total == 0.3 ? 'equal' : 'not equal';",
    options: [
      "A) equal",
      "B) not equal",
      "C) Fatal error",
      "D) Warning: comparison",
    ],
    correct_answer: "B",
    explanation: "0.1 + 0.2 = 0.30000000000000004 in IEEE 754. Use bcmath or round() for precise comparison.",
  },
  {
    id: "php-23",
    type: "multiple_choice",
    difficulty: "hard",
    topic: "php",
    title: "Race condition in file lock",
    description: "What's wrong with this file-based counter?",
    code_snippet: "$count = (int)file_get_contents('counter.txt');\n$count++;\nfile_put_contents('counter.txt', $count);",
    options: [
      "A) No file locking - concurrent requests can overwrite each other",
      "B) file_get_contents returns string, not int",
      "C) Missing file existence check",
      "D) file_put_contents needs append mode",
    ],
    correct_answer: "A",
    explanation: "Without flock(), two requests can read the same value, increment, and one write gets lost.",
  },
  {
    id: "php-24",
    type: "fill_in_blank",
    difficulty: "hard",
    topic: "php",
    title: "PHP 8 match expression",
    description: "What keyword replaces switch with strict comparison?",
    code_snippet: "$result = ???($status) {\n  'active' => 'green',\n  'pending' => 'yellow',\n  default => 'gray',\n};",
    correct_answer: "match",
    explanation: "match is a PHP 8 expression that uses strict comparison and returns a value.",
  },
  {
    id: "php-25",
    type: "multiple_choice",
    difficulty: "hard",
    topic: "php",
    title: "Serialization vulnerability",
    description: "What is dangerous about this code?",
    code_snippet: '$data = unserialize($_COOKIE["user_data"]);',
    options: [
      "A) Object injection - attacker can instantiate arbitrary classes",
      "B) Cookie values are limited to 4KB",
      "C) unserialize is deprecated",
      "D) Cookies can't store serialized data",
    ],
    correct_answer: "A",
    explanation: "Unserializing user input allows object injection attacks that can trigger __wakeup or __destruct methods.",
  },
];

const frontendTickets: Ticket[] = [
  // === EASY ===
  {
    id: "fe-1",
    type: "multiple_choice",
    difficulty: "easy",
    topic: "frontend",
    title: "React useState bug",
    description: "What's wrong with this counter component?",
    code_snippet: "function Counter() {\n  let count = 0;\n  return (\n    <button onClick={() => count++}>\n      Count: {count}\n    </button>\n  );\n}",
    options: [
      "A) Should use useState hook instead of let",
      "B) onClick syntax is wrong",
      "C) Missing return statement",
      "D) count++ is invalid in JSX",
    ],
    correct_answer: "A",
    explanation: "React requires useState for reactive state. Regular variables don't trigger re-renders.",
  },
  {
    id: "fe-2",
    type: "multiple_choice",
    difficulty: "easy",
    topic: "frontend",
    title: "CSS Flexbox alignment",
    description: "How to center a div both horizontally and vertically?",
    code_snippet: ".container {\n  display: flex;\n  ???\n}",
    options: [
      "A) align-items: center; justify-content: center;",
      "B) text-align: center; vertical-align: middle;",
      "C) margin: auto; padding: auto;",
      "D) position: center;",
    ],
    correct_answer: "A",
    explanation: "Flexbox uses align-items and justify-content for centering.",
  },
  {
    id: "fe-3",
    type: "fill_in_blank",
    difficulty: "easy",
    topic: "frontend",
    title: "Array method",
    description: "Which method creates a new array with transformed elements?",
    code_snippet: "const doubled = [1, 2, 3].???(x => x * 2);",
    correct_answer: "map",
    explanation: "Array.map() creates a new array with the results of calling a function on every element.",
  },
  {
    id: "fe-4",
    type: "multiple_choice",
    difficulty: "easy",
    topic: "frontend",
    title: "Equality check",
    description: "What's the difference between == and ===?",
    code_snippet: 'console.log(1 == "1");  // ???\nconsole.log(1 === "1"); // ???',
    options: [
      "A) true, false",
      "B) true, true",
      "C) false, false",
      "D) false, true",
    ],
    correct_answer: "A",
    explanation: "== does type coercion (1 == '1' is true). === checks type and value strictly.",
  },
  {
    id: "fe-5",
    type: "multiple_choice",
    difficulty: "easy",
    topic: "frontend",
    title: "const reassignment",
    description: "What happens when running this code?",
    code_snippet: 'const name = "Alice";\nname = "Bob";',
    options: [
      "A) TypeError: Assignment to constant variable",
      "B) name becomes 'Bob'",
      "C) name stays 'Alice' silently",
      "D) SyntaxError",
    ],
    correct_answer: "A",
    explanation: "const prevents reassignment. To change a variable, use let.",
  },
  {
    id: "fe-6",
    type: "fill_in_blank",
    difficulty: "easy",
    topic: "frontend",
    title: "Template literal",
    description: "What syntax wraps template literals in JavaScript?",
    code_snippet: "const msg = ???Hello ${name}???;",
    correct_answer: "`",
    explanation: "Template literals use backtick (`) characters, not single or double quotes.",
  },
  {
    id: "fe-7",
    type: "multiple_choice",
    difficulty: "easy",
    topic: "frontend",
    title: "Array filter",
    description: "What does this return?",
    code_snippet: "const nums = [0, 1, '', null, 'hello', undefined];\nconst result = nums.filter(Boolean);",
    options: [
      "A) [1, 'hello']",
      "B) [0, 1, '', null, 'hello', undefined]",
      "C) [true, true, false, false, true, false]",
      "D) Error: Boolean is not a function",
    ],
    correct_answer: "A",
    explanation: "filter(Boolean) removes all falsy values (0, '', null, undefined, false, NaN).",
  },
  {
    id: "fe-8",
    type: "multiple_choice",
    difficulty: "easy",
    topic: "frontend",
    title: "CSS box model",
    description: "An element has width: 200px, padding: 20px, border: 5px. What is the total width?",
    code_snippet: ".box {\n  width: 200px;\n  padding: 20px;\n  border: 5px solid black;\n}",
    options: [
      "A) 250px (content-box: 200 + 40 + 10)",
      "B) 200px",
      "C) 225px",
      "D) 270px",
    ],
    correct_answer: "A",
    explanation: "Default box-sizing is content-box. Total = width + left/right padding + left/right border.",
  },
  // === MEDIUM ===
  {
    id: "fe-9",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "frontend",
    title: "useEffect cleanup",
    description: "What's the memory leak in this component?",
    code_snippet: "function Timer() {\n  const [time, setTime] = useState(0);\n  useEffect(() => {\n    setInterval(() => setTime(t => t + 1), 1000);\n  }, []);\n  return <div>{time}</div>;\n}",
    options: [
      "A) Missing cleanup: interval not cleared on unmount",
      "B) useState syntax is wrong",
      "C) setInterval can't use state updater",
      "D) Empty dependency array causes infinite loop",
    ],
    correct_answer: "A",
    explanation: "The interval continues after unmount. Return a cleanup function: return () => clearInterval(id);",
  },
  {
    id: "fe-10",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "frontend",
    title: "JavaScript closure",
    description: "What does this log?",
    code_snippet: 'for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 100);\n}',
    options: ["A) 0, 1, 2", "B) 3, 3, 3", "C) undefined x3", "D) 0, 0, 0"],
    correct_answer: "B",
    explanation: "var is function-scoped. By the time setTimeout fires, the loop has finished and i is 3.",
  },
  {
    id: "fe-11",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "frontend",
    title: "React key prop issue",
    description: "Why might this list have rendering bugs?",
    code_snippet: "function List({ items }) {\n  return items.map((item, index) => (\n    <input key={index} defaultValue={item.name} />\n  ));\n}",
    options: [
      "A) Using index as key causes bugs when list order changes",
      "B) defaultValue is not a valid prop",
      "C) map doesn't work with JSX",
      "D) Missing return statement",
    ],
    correct_answer: "A",
    explanation: "Using array index as key can cause state to persist incorrectly when items are reordered.",
  },
  {
    id: "fe-12",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "frontend",
    title: "Promise error handling",
    description: "What happens if the fetch fails?",
    code_snippet: "async function getData() {\n  const res = await fetch('/api/data');\n  const data = await res.json();\n  return data;\n}",
    options: [
      "A) Unhandled promise rejection - no error handling",
      "B) Returns undefined gracefully",
      "C) fetch automatically retries",
      "D) res.json() catches the error",
    ],
    correct_answer: "A",
    explanation: "There's no try-catch or .catch() to handle network errors or non-OK responses.",
  },
  {
    id: "fe-13",
    type: "fill_in_blank",
    difficulty: "medium",
    topic: "frontend",
    title: "Destructuring",
    description: "Complete the destructuring assignment",
    code_snippet: "const { name, age, ...??? } = user;",
    correct_answer: "rest",
    explanation: "The rest operator (...rest) collects remaining properties into a new object.",
  },
  {
    id: "fe-14",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "frontend",
    title: "Event propagation",
    description: "What happens when clicking the inner div?",
    code_snippet: '<div onClick={() => console.log("outer")}>\n  <div onClick={() => console.log("inner")}>\n    Click me\n  </div>\n</div>',
    options: [
      'A) Logs "inner" then "outer" (bubbling)',
      'B) Logs only "inner"',
      'C) Logs "outer" then "inner"',
      'D) Logs only "outer"',
    ],
    correct_answer: "A",
    explanation: "Events bubble up from the target. Inner fires first, then outer. Use stopPropagation() to prevent.",
  },
  {
    id: "fe-15",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "frontend",
    title: "Object reference trap",
    description: "What does console.log show?",
    code_snippet: "const obj = { count: 0 };\nconst copy = obj;\ncopy.count = 5;\nconsole.log(obj.count);",
    options: [
      "A) 5 - objects are passed by reference",
      "B) 0 - copy is independent",
      "C) undefined",
      "D) Error",
    ],
    correct_answer: "A",
    explanation: "Objects are reference types. Both obj and copy point to the same object in memory.",
  },
  {
    id: "fe-16",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "frontend",
    title: "CSS specificity",
    description: "Which rule wins?",
    code_snippet: '/* Rule 1 */ .btn { color: red; }\n/* Rule 2 */ button.btn { color: blue; }\n/* Rule 3 */ #submit { color: green; }\n\n<button class="btn" id="submit">Click</button>',
    options: [
      "A) green - ID selector has highest specificity",
      "B) blue - element + class is more specific than class alone",
      "C) red - it appears first",
      "D) browser default",
    ],
    correct_answer: "A",
    explanation: "ID selectors (0,1,0,0) beat class selectors (0,0,1,0) and element selectors (0,0,0,1).",
  },
  {
    id: "fe-17",
    type: "fill_in_blank",
    difficulty: "medium",
    topic: "frontend",
    title: "Optional chaining",
    description: "What operator safely accesses nested properties?",
    code_snippet: "const city = user???address???city;",
    correct_answer: "?.",
    explanation: "Optional chaining (?.) short-circuits to undefined if any part is null/undefined.",
  },
  {
    id: "fe-18",
    type: "multiple_choice",
    difficulty: "medium",
    topic: "frontend",
    title: "useCallback purpose",
    description: "When is useCallback actually needed?",
    code_snippet: "const handleClick = useCallback(() => {\n  setCount(c => c + 1);\n}, []);",
    options: [
      "A) When passing callbacks to memoized child components",
      "B) Always - it improves performance",
      "C) Only with async functions",
      "D) Only inside useEffect",
    ],
    correct_answer: "A",
    explanation: "useCallback prevents unnecessary re-renders of React.memo children by keeping the same function reference.",
  },
  // === HARD ===
  {
    id: "fe-19",
    type: "multiple_choice",
    difficulty: "hard",
    topic: "frontend",
    title: "XSS vulnerability",
    description: "Which code is vulnerable to Cross-Site Scripting?",
    code_snippet: '// A\n<div dangerouslySetInnerHTML={{__html: userInput}} />\n\n// B\n<div>{userInput}</div>',
    options: [
      "A) Code A is vulnerable",
      "B) Code B is vulnerable",
      "C) Both are vulnerable",
      "D) Neither is vulnerable",
    ],
    correct_answer: "A",
    explanation: "dangerouslySetInnerHTML renders raw HTML, allowing script injection. JSX auto-escapes by default.",
  },
  {
    id: "fe-20",
    type: "multiple_choice",
    difficulty: "hard",
    topic: "frontend",
    title: "Stale closure in React",
    description: "Why does this always alert 0?",
    code_snippet: "function App() {\n  const [count, setCount] = useState(0);\n  useEffect(() => {\n    const id = setInterval(() => {\n      alert(count);\n    }, 3000);\n    return () => clearInterval(id);\n  }, []);\n  return <button onClick={() => setCount(c => c + 1)}>+</button>;\n}",
    options: [
      "A) Stale closure - count is captured as 0 in the useEffect",
      "B) setInterval doesn't work in React",
      "C) useState doesn't update synchronously",
      "D) Missing count in dependency array causes infinite loop",
    ],
    correct_answer: "A",
    explanation: "Empty deps array means the effect runs once, closing over count = 0 forever.",
  },
  {
    id: "fe-21",
    type: "multiple_choice",
    difficulty: "hard",
    topic: "frontend",
    title: "TypeScript discriminated union",
    description: "What's wrong with this TypeScript code?",
    code_snippet: "type Shape = \n  | { kind: 'circle'; radius: number }\n  | { kind: 'square'; side: number };\n\nfunction area(s: Shape) {\n  if (s.kind === 'circle') return Math.PI * s.radius ** 2;\n  return s.side ** 2;\n}",
    options: [
      "A) Nothing - this is correct discriminated union usage",
      "B) Missing exhaustive check for future variants",
      "C) Can't use ** operator with number type",
      "D) kind should be an enum",
    ],
    correct_answer: "A",
    explanation: "This is a correctly implemented discriminated union. TypeScript narrows the type via kind checks.",
  },
  {
    id: "fe-22",
    type: "multiple_choice",
    difficulty: "hard",
    topic: "frontend",
    title: "Layout thrashing",
    description: "Why is this code slow?",
    code_snippet: "elements.forEach(el => {\n  const height = el.offsetHeight;\n  el.style.height = height * 2 + 'px';\n});",
    options: [
      "A) Forces layout recalculation on every iteration (layout thrashing)",
      "B) forEach is slower than for loop",
      "C) offsetHeight returns a string",
      "D) style.height needs units object",
    ],
    correct_answer: "A",
    explanation: "Reading offsetHeight then writing style forces the browser to recalculate layout each iteration.",
  },
  {
    id: "fe-23",
    type: "multiple_choice",
    difficulty: "hard",
    topic: "frontend",
    title: "Prototype pollution",
    description: "What's the security risk?",
    code_snippet: 'function merge(target, source) {\n  for (const key in source) {\n    target[key] = source[key];\n  }\n  return target;\n}\n\nmerge({}, JSON.parse(\'{"__proto__":{"isAdmin":true}}\'));',
    options: [
      "A) Prototype pollution - can modify Object.prototype",
      "B) JSON.parse can't parse __proto__",
      "C) for...in skips __proto__",
      "D) merge creates a deep copy safely",
    ],
    correct_answer: "A",
    explanation: "Setting __proto__ modifies Object.prototype, affecting all objects globally.",
  },
  {
    id: "fe-24",
    type: "multiple_choice",
    difficulty: "hard",
    topic: "frontend",
    title: "React concurrent rendering",
    description: "What can go wrong with this pattern?",
    code_snippet: "let externalData = null;\n\nfunction Component() {\n  if (!externalData) {\n    externalData = fetchData();\n  }\n  return <div>{externalData.name}</div>;\n}",
    options: [
      "A) Mutable external variable breaks concurrent rendering",
      "B) fetchData is async, can't assign directly",
      "C) Should use useEffect",
      "D) externalData.name could be undefined",
    ],
    correct_answer: "A",
    explanation: "External mutable state shared between renders breaks React's concurrent features (tearing).",
  },
  {
    id: "fe-25",
    type: "fill_in_blank",
    difficulty: "hard",
    topic: "frontend",
    title: "Nullish coalescing assignment",
    description: "What operator assigns only if the left side is null/undefined?",
    code_snippet: "user.name ???= 'Anonymous';",
    correct_answer: "??",
    explanation: "??= (nullish coalescing assignment) assigns only if the left side is null or undefined.",
  },
];

/**
 * Get preset tickets by topic, shuffled with true randomness.
 */
export function getPresetTickets(topic: Topic): Ticket[] {
  let tickets: Ticket[];

  switch (topic) {
    case "php":
      tickets = [...phpTickets];
      break;
    case "frontend":
      tickets = [...frontendTickets];
      break;
    case "mix":
      tickets = [...phpTickets, ...frontendTickets];
      break;
  }

  // Fisher-Yates shuffle with cryptographic-quality randomness
  for (let i = tickets.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [tickets[i], tickets[j]] = [tickets[j], tickets[i]];
  }

  // Assign unique IDs to avoid collisions between sessions
  const sessionId = Date.now().toString(36);
  tickets = tickets.map((t, idx) => ({
    ...t,
    id: `${t.id}-${sessionId}-${idx}`,
  }));

  return tickets;
}
